const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);
const photo=$('#photo'),dialogue=$('#dialogue'),speaker=$('#speaker'),line=$('#line'),choices=$('#choices'),next=$('#next'),prevLine=$('#prevLine');
const analyticsVersion='2026-08-24-v3';
function track(event,properties={}){try{if(localStorage.getItem('clockAnalyticsConsent')==='accepted'&&window.posthog?.capture)posthog.capture(event,{...properties,game_version:analyticsVersion})}catch(error){console.debug('Analytics unavailable')}}
const state={playerName:localStorage.getItem('clockPlayerName')||'',day:1,phase:'campus',clues:new Set(),d2clues:new Set(),d2talk:new Set(),children:new Set(),clay:new Set(),checkpoints:new Set(),briefRead:false,reported:false,rearIntroSeen:false,phoneView:'home',phoneMode:'brief',docSource:'bag',plannerStep:0,decisions:[],resources:{},outcome:'',dayStartedAt:0,gameStartedAt:0,scores:{story:0,resource:0,support:0,cross:0},unlockedDay:Number(localStorage.getItem('clockUnlockedDay')||1)};
const sceneCheckpoints={rear:'rear_building',team:'children',search:'toilet_search',compare:'shoe_compare',day2rear:'new_footprint',day2map:'campus_exploration',day2drawing:'drawing',day2plantkids:'plant_search',day2plants:'plant_compare',day2alan:'along_found'};
function markCheckpoint(checkpoint){const key=`${state.day}:${checkpoint}`;if(state.checkpoints.has(key))return;state.checkpoints.add(key);track('checkpoint_reached',{day:state.day,checkpoint})}
function startDay(day){state.day=day;state.dayStartedAt=Date.now();state.checkpoints.clear();track('day_started',{day})}
function elapsedSeconds(startedAt){return startedAt?Math.max(1,Math.round((Date.now()-startedAt)/1000)):null}
function completeDay(day,extra={}){track('day_completed',{day,duration_seconds:elapsedSeconds(state.dayStartedAt),...extra})}
const sceneHistory=[];let sceneHistoryIndex=-1;
const notes={door:['虛掩的側門','昨天場勘離開時確實鎖過，今天門鎖卻沒有扣緊。'],crumbs:['零食包裝碎屑','牆邊留著幾片包裝碎屑，不像總務工作時留下的東西。'],prints:['後棟腳印','鞋底有明顯鋸齒刻痕，痕跡已經不算新。'],laian:['賴安離隊','他說要去樓下廁所，最後卻從後棟方向回來。'],shoes:['鞋印比對','賴安的鞋底偏平滑，與後棟鋸齒狀鞋印不吻合。'],truth:['賴安真正隱瞞的事','他只是想看獨角仙，卻擔心承認童趣會被覺得幼稚。'],d2foot:['新鮮腳印','新腳印停在上鎖的側門外，接著轉向花圃與圍牆邊。'],d2map:['校園探索分工','賴安會照顧隊伍、連恩擅長凝聚大家、洛祈勇於嘗試、芮琪習慣安靜記錄。'],d2drawing:['第五個人','芮琪畫了五個朋友；站在一旁的人背著鼓鼓的舊書包。'],d2plant:['咸豐草種子','腳印照片裡的針狀種子，與舊候車亭旁的咸豐草最相似。'],d2alan:['阿龍','四個孩子以前的朋友；他不是陌生闖入者，而是一直想靠近大家的人。']};
const scenes={
 campus:{place:'合興國小・穿堂',img:'hexing-campus.webp',spots:[['tree',0,5,38,62,'老榕樹','樹蔭下還沒有人，營隊物資整齊放在走廊邊。','look'],['hall',38,17,38,55,'穿堂','集合場地還很安靜，距離孩子報到還有半小時。','look'],['rearEntry',68,12,32,68,'通往後棟','走廊深處通往很久沒有使用的後棟。','rear']]},
 rear:{place:'合興國小・後棟',img:'rear-corridor.webp',spots:[['door',5,22,24,43,'側門','側門沒有鎖緊，只是虛掩著。你記得昨天離開時有確實上鎖。','clue'],['crumbs',48,61,29,24,'牆邊地面','牆腳有幾片零食包裝碎屑，看起來不像總務留下的。','clue'],['prints',18,62,31,34,'地面痕跡','灰塵上留著一串不算新的腳印，鞋底有明顯鋸齒刻痕。','clue'],['room',71,18,29,55,'舊教室','裡面堆著課桌椅。這就是主任請你們搬的東西。','look'],['window',36,10,33,38,'窗戶','窗上積著一層灰，看得出後棟已經很久沒有使用。','look']]},
 team:{place:'09:30・自我介紹小卡',img:'team-classroom.webp',spots:[['laian',0,48,30,48,'賴安','laian-card.webp','child'],['lien',27,36,30,37,'連恩','lien-card.webp','child'],['luoqi',43,31,28,36,'洛祈','luoqi-card.webp','child'],['richi',67,42,33,50,'芮琪','richi-card.webp','child']]},
 search:{place:'10:40・通往後棟的走廊',img:'laian-distant.webp',spots:[['laianReturn',49,39,22,30,'遠處的人影','走廊盡頭露出一個小小的身影，好像是賴安。','return'],['corridor',0,12,48,77,'走廊','你沿著走廊一路找來，附近都沒有其他孩子。','look']]},
 compare:{place:'13:50・比對兩張照片',img:'footprint-photo.webp',spots:[['photoPrint',48,53,45,37,'後棟腳印','你放大後棟的泥腳印。鞋底中央是交錯的鋸齒格狀紋路。','compare'],['phoneShot',18,48,42,42,'手機裡的鞋底照片','你打開剛才在黏土課拍到的照片。賴安的鞋底是整齊的水平橫紋。','compare']]},
 dismissal:{place:'15:00・賦歸',img:'dismissal.webp',spots:[['luoqiLook',0,35,42,62,'隊伍最後的洛祈','洛祈沒有跟上隊伍，只是望著後棟方向。','dismiss'],['line',42,35,58,55,'賦歸隊伍','孩子們背起書包，隊輔正在核對接送名單。','look']]},
 day2rear:{place:'DAY 2・重新上鎖的後棟',img:'day2-rear-v2.webp',spots:[['d2foot',18,55,66,43,'花圃裡的新腳印','腳印停在上鎖的側門外，接著朝花圃深處偏去。泥痕旁還黏著幾顆細長的黑色種子。','d2foot']]},
 day2map:{place:'08:20・校園大探索｜地圖關',img:'day2-explore-map-v2.webp',spots:[['mapLaian',0,27,25,66,'賴安','賴安握著地圖左側，先確認大家目前的位置。','d2map'],['mapLien',24,27,25,66,'連恩','連恩指著地圖中央，招呼大家靠近一起看。','d2map'],['mapLuoqi',48,25,25,68,'洛祈','洛祈抬頭觀察樓梯，想確認地圖方向。','d2map'],['mapRiqi',72,28,28,65,'芮琪','芮琪比對地圖上的操場和眼前樓梯。','d2map']]},
 day2tree:{place:'09:10・校園大探索｜榕樹關',img:'day2-explore-tree-v2.webp',spots:[['treeRiqi',0,25,31,69,'芮琪','芮琪站在左側，把每個人的發現寫進紀錄板。','d2tree'],['treeLuoqi',24,52,43,46,'洛祈','洛祈蹲在正中央的樹根間，伸手取出線索卡。','d2tree'],['treeLien',38,21,31,43,'連恩','連恩站在後方，指著洛祈找到的位置。','d2tree'],['treeLaian',68,24,32,67,'賴安','賴安在右側拿著隊伍的答案袋，等大家確認。','d2tree']]},
 day2drawing:{place:'11:00・樹蔭下',img:'day2-richi-drawing-consistent.webp',spots:[['d2paper',18,31,70,64,'正在畫畫的芮琪','芮琪沒有加入吵鬧的聊天，只是安靜地在速寫本上畫著。','d2drawing']]},
 day2drawingReveal:{place:'11:05・找出畫裡不對勁的地方',img:'day2-richi-reveal-consistent.webp',spots:[['draw1',8,52,18,28,'第一個孩子','這是第三小隊的朋友。','drawingWrong'],['draw2',25,52,18,28,'第二個孩子','這也是第三小隊的朋友。','drawingWrong'],['draw3',42,52,18,28,'中間的孩子','畫裡的女孩是芮琪自己。','drawingWrong'],['draw4',59,52,18,28,'第四個孩子','這也是現在小隊裡的人。','drawingWrong'],['draw5',71,50,23,32,'背書包的第五個孩子','現在的第三小隊只有四個人，畫裡卻多了一個背書包的男孩。','drawingRight']]},
 day2plantkids:{place:'13:40・校園植物大調查',img:'day2-plant-kids-v2.webp',spots:[['plantKidLaian',0,45,43,50,'賴安','賴安在左下方蹲著，研究圓圓的帶刺果實。','plantKid'],['plantKidLien',29,15,31,43,'連恩','連恩站在中央，拿著兩片葉子仔細比較。','plantKid'],['plantKidLuoqi',61,15,39,43,'洛祈','洛祈站在右上方，觀察樹叢裡的枝葉。','plantKid'],['plantKidRiqi',45,49,55,47,'芮琪','芮琪在右下方，把大家的發現逐項記下。','plantKid']]},
 day2plants:{place:'13:35・默默比對照片',img:'day2-plant-puzzle-consistent.webp',spots:[['plantBurr',0,36,21,39,'左側的圓刺果實','果實圓而密集，和照片裡細長的黑色種子不同。','plantWrong'],['plantHeart',18,35,22,38,'大片心形葉','只有寬大的葉片，沒有照片中的針狀種子。','plantWrong'],['plantClover',38,36,22,37,'低矮小葉草','葉片貼地成片生長，種子外形也不相同。','plantWrong'],['plantFoxtail',57,35,23,40,'高高的狗尾草','穗狀花序柔軟蓬鬆，並不是會黏褲腳的黑色倒鉤種子。','plantWrong'],['plantRight',78,34,22,45,'最右側的小白花','白色小花旁長著細長、帶倒鉤的黑色種子，和照片裡的一樣。','plantRight']]},
 day2board:{place:'15:10・成果展看板',img:'day2-board.webp',spots:[['d2lienLook',0,18,47,72,'連恩的視線','連恩停下手上的工作，緊張地望向後棟。','d2board']]},
 day2alan:{place:'15:30・後棟小路',img:'day2-alan-hidden.webp',spots:[['d2alan',48,48,26,28,'遠處的人影','灌木後方站著一個背舊書包的男孩。他很小心地朝校園裡張望。','d2alan']]}
};
const childScripts={
 laian:{name:'賴安',intro:[{t:'賴安把整盒彩色筆推到桌子中央，一枝一枝分給其他人，最後才替自己挑了一枝。'},{s:'艾莉',t:'你很會照顧大家耶。'},{s:'賴安',t:'還好啦，先給他們選比較不會吵架。'}],question:'你想怎麼回應？',opts:[{label:'問他：「你平常也都先幫別人嗎？」',value:'ask'},{label:'先不追問，謝謝他的幫忙',value:'observe'}],answers:{ask:[{s:'你',t:'你平常也都先幫別人嗎？'},{s:'賴安',t:'嗯……這樣大人比較不用一直管我們。'},{t:'他回答得很自然，像是早已習慣先確認其他人都沒問題。'}],observe:[{s:'你',t:'謝謝你幫忙，記得你自己也要選喜歡的顏色。'},{s:'賴安',t:'我都可以，剩下的就好。'}]}},
 lien:{name:'連恩',intro:[{t:'連恩一邊畫自介卡，一邊把橘色蠟筆舉到芮琪面前。'},{s:'連恩',t:'用這枝跟妳換一塊餅乾，超划算吧？'},{s:'芮琪',t:'這本來就是公用的耶。'},{s:'連恩',t:'被發現了。'}],question:'你想怎麼回應？',opts:[{label:'笑著問：「你第一天就開始做生意喔？」',value:'ask'},{label:'先看看他接下來要做什麼',value:'observe'}],answers:{ask:[{s:'你',t:'你第一天就開始做生意喔？'},{s:'連恩',t:'交朋友要有效率啊！我很快就會跟大家熟了。'}],observe:[{t:'連恩沒多久就和隔壁隊借到膠帶，回來時還多認識了兩個人。'},{s:'艾莉',t:'他的交際能力也太快了吧。'}]}},
 luoqi:{name:'洛祈',intro:[{t:'洛祈自己的卡片只畫了一半，已經第三次站起來看別人在畫什麼。'},{s:'連恩',t:'你又偷看。'},{s:'洛祈',t:'我是在巡視大家的進度。'}],question:'你想怎麼回應？',opts:[{label:'問他：「那你的進度呢？」',value:'ask'},{label:'提醒他不要打擾別人',value:'observe'}],answers:{ask:[{s:'你',t:'巡視員，那你自己的進度呢？'},{s:'洛祈',t:'快好了啦。我先參考一下大家怎麼畫。'},{s:'連恩',t:'你那張明明只有名字。'},{s:'洛祈',t:'名字很重要耶！'}],observe:[{s:'你',t:'可以看，但不要壓到別人的圖。'},{s:'洛祈',t:'遵命。'},{t:'他坐回去不到半分鐘，又忍不住抬起頭。'}]}},
 richi:{name:'芮琪',intro:[{t:'芮琪的名牌寫得端正，資料照順序夾好，桌上還擺著一整套新文具。老師剛才問的題目，她幾乎每一題都答得出來。'},{s:'芮琪',t:'我畫完了。你們缺顏色可以跟我借，我有兩盒。'},{s:'艾莉',t:'妳準備得好齊全，而且反應也很快耶。'},{t:'她看起來聰明、有條理，又完全不需要大人提醒。'}],question:'你想怎麼回應？',opts:[{label:'問她：「妳每次都這麼快做完嗎？」',value:'ask'},{label:'稱讚她：「妳真的又聰明又有條理」',value:'observe'}],answers:{ask:[{s:'你',t:'妳每次都這麼快做完嗎？'},{s:'芮琪',t:'差不多。我喜歡先照順序做，做完就可以畫自己的東西。'},{t:'她點點頭，又低頭把剛才用過的筆依照顏色放回盒子裡。'}],observe:[{s:'你',t:'妳真的又聰明又有條理，感覺什麼都難不倒妳。'},{s:'芮琪',t:'還好啦，這些我都會。'}]}}
};
function hideAll(){['cover','guide','nameEntry','preSurvey','postSurvey','chapters','prologue','flyer','explore','dialogue','phone','bag','document','clueDetail','notebook','ending','endingTwo','planner','result','thanks'].forEach(id=>$('#'+id)?.classList.add('hidden'));$('#bagBtn').classList.add('hidden');$('#sceneNext').classList.add('hidden');$('#sceneNext').classList.remove('primary-center')}
function updateChapterButtons(){[['dayOne',1],['dayTwo',2],['dayThree',3]].forEach(([id,day])=>{const b=$('#'+id),open=state.unlockedDay>=day;b.disabled=!open;b.querySelector('span').textContent=open?'開始':'🔒'})}
function unlockDay(day){state.unlockedDay=Math.max(state.unlockedDay,day);localStorage.setItem('clockUnlockedDay',state.unlockedDay);updateChapterButtons()}
function page(id){hideAll();$('#hud').classList.add('hidden');$('#'+id).classList.remove('hidden');if(id==='chapters')updateChapterButtons();if(id==='nameEntry'){$('#playerName').value=state.playerName;setTimeout(()=>$('#playerName').focus(),80)}if(id==='preSurvey'){photo.style.backgroundImage='url("prologue-chat.webp")';track('pretest_opened')}if(id==='postSurvey'){photo.style.backgroundImage='url("day3-group-photo-consistent.webp")';track('posttest_opened')}if(id==='cover')photo.style.backgroundImage='url("hexing-campus.webp")';if(id==='prologue')photo.style.backgroundImage='url("prologue-chat.webp")'}
$$('[data-go]').forEach(b=>b.onclick=()=>page(b.dataset.go));
function say(lines,done){dialogue.classList.remove('hidden');let i=0;const show=()=>{const x=lines[i];if(x.img)photo.style.backgroundImage=`url("${x.img}")`;speaker.textContent=x.s==='你'?(state.playerName||'你'):(x.s||'');line.textContent=x.t;choices.innerHTML='';prevLine.classList.toggle('hidden',i===0);prevLine.onclick=()=>{if(i>0){i--;show()}};next.classList.remove('hidden');next.textContent=i===lines.length-1?'繼續':'下一句';next.onclick=()=>{if(++i<lines.length)show();else{dialogue.classList.add('hidden');prevLine.classList.add('hidden');done&&done()}}};show()}
function choose(text,opts,done){dialogue.classList.remove('hidden');speaker.textContent='';line.textContent=text;prevLine.classList.add('hidden');next.classList.add('hidden');choices.innerHTML='';opts.forEach(o=>{const b=document.createElement('button');b.textContent=o.label;b.onclick=()=>{choices.innerHTML='';dialogue.classList.add('hidden');done(o.value)};choices.append(b)})}
function resetSceneHistory(){sceneHistory.length=0;sceneHistoryIndex=-1}
function updateSceneNav(){const forward=$('#sceneForward');forward.classList.toggle('hidden',sceneHistoryIndex>=sceneHistory.length-1)}
function showScene(key,track=true){if(track){if(sceneHistory[sceneHistoryIndex]!==key){sceneHistory.splice(sceneHistoryIndex+1);sceneHistory.push(key);sceneHistoryIndex=sceneHistory.length-1}}state.phase=key;if(sceneCheckpoints[key])markCheckpoint(sceneCheckpoints[key]);const s=scenes[key];hideAll();$('#hud').classList.remove('hidden');$('#explore').classList.remove('hidden');$('#hudDay').textContent=`DAY ${state.day}`;updateSceneNav();if(key==='campus')$('#bagBtn').classList.remove('hidden');if(key==='rear'&&['door','crumbs','prints'].every(k=>state.clues.has(k))&&!state.reported){$('#sceneNext').textContent='三處都看完了，和艾莉整理';$('#sceneNext').classList.add('primary-center');$('#sceneNext').classList.remove('hidden')}if(key==='compare'&&state.clay.has('photoPrint')&&state.clay.has('phoneShot')){$('#sceneNext').textContent='完成腳印比對';$('#sceneNext').classList.remove('hidden')}const freeNext={team:'結束自由互動，前往大下課',day2map:'前往下一關',day2tree:'完成校園探索',day2plantkids:'繼續植物調查'};if(freeNext[key]){$('#sceneNext').textContent=freeNext[key];$('#sceneNext').classList.remove('hidden')}$('#place').textContent=s.place;photo.style.backgroundImage=`url("${s.img}")`;const box=$('#spots');box.innerHTML='';s.spots.forEach(([id,x,y,w,h,title,text,type])=>{const b=document.createElement('button');b.className='spot';b.dataset.spot=id;b.setAttribute('aria-label',title);Object.assign(b.style,{left:x+'%',top:y+'%',width:w+'%',height:h+'%'});b.onclick=()=>tap(id,title,text,type);box.append(b)});$('#explore .tap-help')?.remove();$('#explore .evidence-inset')?.remove();if(key==='day2plants'){const e=document.createElement('div');e.className='evidence-inset';e.innerHTML='<small>早上拍下的照片</small>';$('#explore').append(e)}refreshSceneHint(key)}
function cameraSnap(){const f=$('#cameraFlash');f.classList.remove('snap');void f.offsetWidth;f.classList.add('snap');setTimeout(()=>f.classList.remove('snap'),450)}
function refreshSceneHint(key){
 const old=$('#explore .tap-help');if(old)old.remove();
 const rearFound=['door','crumbs','prints'].filter(k=>state.clues.has(k)).length;
 const compared=state.clay.has('photoPrint')&&state.clay.has('phoneShot');
 let hint='';
 if(key==='campus')hint=state.briefRead?'沿著走廊找找後棟入口。':'背包裡的手機正在震動，打開背包查看。';
 else if(key==='rear')hint=`原本這裡門緊鎖、乾乾淨淨。找出空間中三個不尋常的地方（${rearFound}/3）`;
 else if(key==='team')hint='可以自由和孩子互動；準備好後，點「前往大下課」。';
 else if(key==='search'&&!state.clues.has('laian'))hint='找找賴安在哪裡';
 else if(key==='compare'&&!compared)hint='請比對兩張照片';
 else if(key==='dismissal')hint='點擊落在隊伍最後的孩子';
 else if(key==='day2rear'&&!state.d2clues.has('d2foot'))hint='點擊花圃裡的新腳印，拍下線索';
 else if(key==='day2map')hint='可以和每個孩子聊聊；準備好後，點「前往下一關」。';
 else if(key==='day2tree')hint='看看孩子們怎麼解題；準備好後，點「完成校園探索」。';
 else if(key==='day2drawing'&&!state.d2clues.has('d2drawing'))hint='點擊正在畫畫的芮琪';
 else if(key==='day2drawingReveal'&&!state.d2clues.has('d2drawing'))hint='圈出畫裡和現在小隊對不上的地方';
 else if(key==='day2plantkids')hint='聽聽孩子們的發現；準備好後，點「繼續植物調查」。';
 else if(key==='day2plants'&&!state.d2clues.has('d2plant'))hint='點選最符合早上照片線索的植物';
 else if(key==='day2board'&&!state.d2clues.has('d2board'))hint='連恩好像注意到什麼，點擊他查看';
 else if(key==='day2alan'&&!state.d2clues.has('d2alan'))hint='灌木附近有人影，找出躲在後棟小路的孩子';
 if(hint){const h=document.createElement('div');h.className='tap-help';h.textContent=hint;$('#explore').append(h)}
}
function tap(id,title,text,type){
 if(type==='rear'){if(!state.briefRead)return toast('手機還在背包裡震動。');showScene('rear');if(!state.rearIntroSeen){state.rearIntroSeen=true;say([{s:'艾莉',t:'這裡很久沒用了，怎麼感覺有人來過？'},{s:'你',t:'先別搬桌椅。畫面有三個異常：側門、牆邊地面和左下方腳印，分別點開看看。'}],()=>showScene('rear'))}return}
 if(type==='clue'){const first=!state.clues.has(id);state.clues.add(id);if(first){updateCount();track('clue_found',{day:1,clue:id})}hideAll();$('#clueDetail').classList.remove('hidden');$('#clueTitle').textContent=title;$('#clueText').innerHTML=`<p>${text}</p>`;return}
 if(type==='child'){openChild(id,text);return}
 if(type==='return'){state.clues.add('laian');updateCount();photo.style.backgroundImage='url("laian-return.webp")';say([{s:'你',t:'賴安！你去哪裡了？',img:'laian-return.webp'},{s:'賴安',t:'……我去後棟看獨角仙。',img:'laian-return.webp'},{s:'你',t:'下次不可以擅自離隊，聽到沒有？'},{s:'賴安',t:'知道了……'},{t:'下午黏土課，你想起後棟腳印，趁賴安伸腳時拍下鞋底。',img:'laian-shoe-sole.webp'},{s:'艾莉',t:'把它和早上的腳印比比看。'},{t:'你回到後棟補拍腳印，準備比對兩張照片。',img:'footprint-photo.webp'}],()=>showScene('compare'));return}
 if(type==='compare'){state.clay.add(id);const evidenceImg=id==='phoneShot'?'laian-shoe-sole.webp':'footprint-photo.webp';say([{s:title,t:text,img:evidenceImg}],()=>showScene('compare'));return}
 if(type==='d2foot'){state.d2clues.add('d2foot');updateCount();say([{t:'你蹲下查看。新的腳印停在門外，完全沒有跨過上鎖的側門。',img:'day2-rear-v2.webp'},{s:'艾莉',t:'所以他今天沒有從門進去。你看，泥痕往花圃那邊偏了。'},{s:'你',t:'圍牆底下有個很小的裂口……不是正常出入口，但小孩可能勉強擠得過去。'},{t:'你拿出手機，讓腳印、泥痕和旁邊幾顆細長的黑色種子一起進入取景框。',img:'day2-footprint-camera.webp'}],()=>{cameraSnap();setTimeout(()=>say([{t:'喀擦。照片定格在相簿裡。'},{t:'08:20，孩子到齊後，第二天的校園大探索闖關開始。',img:'day2-explore-map-v2.webp'}],()=>showScene('day2map')),460)});return}
 if(type==='d2map'){state.d2talk.add(id);const scripts={mapLaian:[{s:'賴安',t:'先確認位置再走，今天不會再走錯。'},{s:'你',t:'好，你負責看方向。'}],mapLien:[{s:'連恩',t:'大家靠過來，我把地圖轉成同一個方向。'},{s:'你',t:'很好，別讓隊伍分散。'}],mapLuoqi:[{s:'洛祈',t:'我到第一個樓梯平台探路，可以嗎？'},{s:'你',t:'可以，但要讓大家看得到你。'}],mapRiqi:[{s:'芮琪',t:'補習班做過類似的地圖題，媽媽昨晚也陪我先看過路線。'},{s:'你',t:'難怪妳這麼快找到方向。'}]};say(scripts[id].map((x,i)=>i?x:{...x,img:'day2-explore-map-v2.webp'}),()=>showScene('day2map'));return}
 if(type==='d2tree'){state.d2talk.add(id);const scripts={treeLaian:[{s:'賴安',t:'卡片先放答案袋，才不會弄丟。'},{s:'你',t:'好，最後記得一起確認答案。'}],treeLien:[{s:'連恩',t:'洛祈找到卡片了！大家一起來看。'},{s:'你',t:'你很會把隊伍叫回來。'}],treeLuoqi:[{s:'洛祈',t:'大家都看高處，我看樹根，真的找到了！'},{s:'你',t:'這個想法很有用。'}],treeRiqi:[{s:'芮琪',t:'我把每一關的發現分開記，等等比較不會忘。'},{s:'你',t:'安靜記錄也是重要的工作。'}]};say(scripts[id].map((x,i)=>i?x:{...x,img:'day2-explore-tree-v2.webp'}),()=>showScene('day2tree'));return}
 if(type==='plantKid'){state.d2talk.add(id);const scripts={plantKidLaian:[{s:'賴安',t:'這個果實是圓的，照片裡的種子是一根一根。'},{s:'你',t:'好，先排除這一種。'}],plantKidLien:[{s:'連恩',t:'這片葉子像愛心，我先記住位置。'},{s:'你',t:'可以，但還要比對種子。'}],plantKidLuoqi:[{s:'洛祈',t:'我可以翻開葉子找嗎？'},{s:'艾莉',t:'從旁邊看就好，不碰不認識的植物。'}],plantKidRiqi:[{s:'芮琪',t:'我把三個位置和種子形狀都畫下來了。'},{s:'你',t:'等等就照妳的紀錄比對。'}]};say(scripts[id].map((x,i)=>i?x:{...x,img:'day2-plant-kids-v2.webp'}),()=>showScene('day2plantkids'));return}
 if(type==='d2drawing'){drawingPuzzle();return}
 if(type==='drawingWrong'){toast('這個人看起來是現在小隊裡的成員。再看看其他地方。');return}
 if(type==='drawingRight'){state.d2clues.add('d2drawing');updateCount();say([{s:'你',t:'這個背書包的男孩是誰？我們這一隊現在不是只有四個人嗎？',img:'day2-richi-reveal-consistent.webp'},{s:'芮琪',t:'因為以前不是只有四個。還有一個人常常跟我們一起玩。'},{s:'你',t:'那他後來怎麼沒有再跟你們一起參加了？'},{t:'芮琪低頭摸了摸紙張邊緣，沒有回答，只把畫本輕輕闔上。'},{t:'13:20，下午的植物大調查開始。四個孩子拿著紀錄板走在前面，分頭觀察步道兩旁的植物。',img:'day2-plant-kids-v2.webp'}],()=>showScene('day2plantkids'));return}
 if(type==='plantWrong'){say([{s:title,t:text,img:'day2-plant-puzzle-consistent.webp'},{s:'艾莉',t:'形狀不太一樣。再看看照片裡那種細長、會黏住衣服的種子。'}],()=>showScene('day2plants'));return}
 if(type==='plantRight'){state.d2clues.add('d2plant');updateCount();say([{s:'你',t:'找到了。這些咸豐草的黑色針狀種子，和腳印旁的一模一樣。',img:'day2-plant-puzzle-consistent.webp'},{s:'艾莉',t:'而且它只集中在舊候車亭和後棟外側這一帶。留下腳印的人，是從這條路過來的。'},{t:'15:10，大家回教室布置成果展看板。連恩貼到一半，忽然望向後棟。',img:'day2-board.webp'}],()=>showScene('day2board'));return}
 if(type==='d2board'){state.d2clues.add('d2board');say([{t:'連恩把最後一張植物照片貼上看板，手卻忽然停在半空中。他越過窗戶，往後棟方向看了好幾秒。',img:'day2-board.webp'},{s:'你',t:'連恩，你在看什麼？'},{s:'連恩',t:'沒有啊……我只是看外面。'},{t:'你順著他的視線望去，正好是舊候車亭小路通往後棟的方向。早上的腳印、芮琪畫裡的第五個人，慢慢在腦中連了起來。'},{s:'你',t:'艾莉，妳先陪大家把看板貼完。我去後棟確認一下，很快回來。'},{s:'艾莉',t:'好，有狀況就馬上叫我。'},{t:'你沿著連恩剛才的視線走進後棟小路。樹影和灌木之間，似乎有個很小的人影。',img:'day2-alan-hidden.webp'}],()=>showScene('day2alan'));return}
 if(type==='d2alan'){state.d2clues.add('d2alan');updateCount();alanConversation();return}
 if(type==='dismiss'){say([{t:'洛祈落在隊伍最後，望著後棟的方向站了幾秒。'},{s:'你',t:'洛祈，跟上囉！'},{t:'他像是突然回神，抓緊背包跑回隊伍。'},{s:'艾莉',t:'他剛剛在看什麼？'},{s:'你',t:'不知道。可能只是又在放空吧。'},{t:'你卻再次想起那串不屬於賴安的腳印。後棟附近，可能還有另一個人來過。'}],()=>{completeDay(1);unlockDay(2);page('ending')});return}
 say([{s:title,t:text}],()=>showScene(state.phase))
}
function openChild(id,img){const d=childScripts[id];hideAll();$('#hud').classList.remove('hidden');$('#place').textContent=d.name;photo.style.backgroundImage=`url("${img}")`;say(d.intro,()=>choose(d.question,d.opts,v=>{track('child_choice',{day:1,child:id,choice:v});say(d.answers[v],()=>{state.children.add(id);showScene('team')})}))}
function teamArrival(){hideAll();$('#hud').classList.remove('hidden');$('#place').textContent='08:00・第三小隊報到';photo.style.backgroundImage='url("team-arrival.webp")';say([{t:'08:00，第三小隊的四個孩子到齊，依序自我介紹。',img:'team-arrival.webp'},{s:'賴安',t:'我是五年級賴安，喜歡自然課和找小動物，也可以幫忙發材料。',img:'laian-intro.webp'},{s:'連恩',t:'我是五年級連恩，喜歡打球、聊天和認識新朋友。',img:'lien-intro.webp'},{s:'洛祈',t:'我是四年級洛祈，喜歡體育課，也喜歡到處找好玩的東西。',img:'luoqi-intro.webp'},{s:'芮琪',t:'我是五年級芮琪，喜歡畫畫和整理東西，也有多帶文具。',img:'richi-intro.webp'},{s:'艾莉',t:'接下來三天，請大家多多指教。',img:'team-arrival.webp'},{t:'破冰結束後，上午的自我介紹小卡課開始。',img:'team-classroom.webp'}],()=>showScene('team'))}
function afterChildren(){say([{s:'艾莉',t:'四個孩子個性差好多。芮琪準備得最完整，看起來最不用操心。',img:'team-classroom.webp'},{t:'10:30，大下課。賴安說這層廁所都有人，急著問能不能下樓。',img:'restroom-full.webp'},{s:'你',t:'可以，快去快回，不要亂跑！'},{t:'五分鐘後，賴安仍沒回來。你急忙下樓找人。',img:'restroom-search.webp'},{t:'樓下廁所沒有人回應，你只好一路找到後棟。'}],()=>showScene('search'))}
function concernReport(){hideAll();$('#hud').classList.remove('hidden');say([{s:'艾莉',t:'昨天門是我們親手鎖的。現在門開著，裡面又有零食碎屑和小孩子大小的腳印。'},{s:'你',t:'如果有人能隨便進來，營隊開始後孩子跑到後棟會很危險。'},{s:'艾莉',t:'先拍下來回報主任，請學校確認門鎖和出入紀錄。'}],()=>openPhone('report'))}
function openBag(){hideAll();const bag=$('#bag');bag.style.backgroundImage='url("open-backpack-map.webp")';bag.classList.remove('hidden')}
function openDocument(kind,source='bag'){state.docSource=source;hideAll();$('#document').classList.remove('hidden');if(kind==='schedule'){$('#docType').textContent='備忘錄';$('#docTitle').textContent='三日營隊行程';$('#docBody').innerHTML='<div class="schedule-grid"><div class="schedule-day"><b>第一天｜認識彼此</b><p>08:00 開營與破冰</p><p>09:30 自我介紹小卡</p><p>13:40 創意黏土工坊</p><p>15:00 賦歸</p></div><div class="schedule-day"><b>第二天｜校園探索</b><p>08:20 校園闖關</p><p>09:50 自然拓印</p><p>13:40 植物觀察</p><p>15:10 成果展看板</p></div><div class="schedule-day"><b>第三天｜成果與告別</b><p>08:20 回憶紀念冊</p><p>09:50 全員總決戰</p><p>11:00 成果發表</p><p>13:00 結業式</p></div></div>'}else{$('#docType').textContent='學校提供資料';$('#docTitle').textContent='合興國小場地圖';$('#docBody').innerHTML='<div class="map-card"><div class="map-block map-front">校門／穿堂<br>前棟教室</div><div class="map-block map-field">操場與老榕樹</div><div class="map-path"></div><div class="map-block map-rear">後棟<br>側門／舊教室</div></div>'}}
function openPhone(mode='brief'){state.phoneMode=mode;state.phoneView='home';hideAll();$('#phone').classList.remove('hidden');renderPhoneHome()}
function renderPhoneHome(){state.phoneView='home';$('#phoneTitle').textContent='';const guide=state.phoneMode==='report'?'<div class="phone-guide">請開啟 LINE，回報給營隊主任</div>':'';$('#messages').innerHTML=guide+'<div class="phone-home"><div class="phone-clock"><small>8月18日　星期二</small><b>07:32</b></div><div class="phone-apps"><button id="lineApp"><i class="app-icon">LINE</i><span>LINE</span></button><button id="notesApp"><i class="app-icon notes-icon">備忘錄</i><span>備忘錄</span></button><button id="cameraApp"><i class="app-icon camera-icon">相機</i><span>相機</span></button></div></div>';$('#lineApp').onclick=renderContacts;$('#notesApp').onclick=()=>openDocument('schedule','phone');$('#cameraApp').onclick=()=>toast('目前沒有需要拍攝的東西。')}
function renderContacts(){state.phoneView='list';$('#phoneTitle').textContent='LINE';const unread=state.briefRead?'':'<span class="unread">1</span>',guide=state.phoneMode==='report'?'<div class="phone-guide">請點擊「營隊主任」回報後棟狀況</div>':'';$('#messages').innerHTML=guide+`<div class="chat-list"><button class="chat-row" id="directorChat"><span class="avatar">主任</span><span><b>營隊主任</b><small>${state.phoneMode==='report'?'桌椅找到了嗎？':'你們到學校了嗎？'}</small></span>${unread}</button><button class="chat-row" id="allyChat"><span class="avatar">艾莉</span><span><b>艾莉</b><small>我在穿堂這邊～</small></span></button></div>`;$('#directorChat').onclick=renderDirector;$('#allyChat').onclick=()=>toast('艾莉就在你旁邊。')}
function renderDirector(){state.phoneView='chat';$('#phoneTitle').textContent='營隊主任';const m=$('#messages');if(state.phoneMode==='report'){m.innerHTML='<div class="msg"><div class="avatar">主任</div><div class="bubble">桌椅找到了嗎？</div></div>';const b=document.createElement('button');b.className='send-report';b.textContent='拍照並回報後棟狀況';b.onclick=sendReport;m.append(b);return}m.innerHTML='<div class="msg"><div class="avatar">主任</div><div class="bubble">你們到學校了嗎？</div></div>';if(!state.briefRead){const b=document.createElement('button');b.className='send-report';b.textContent='回覆：到了！';b.onclick=sendArrival;m.append(b)}else m.innerHTML+='<div class="msg me"><div class="bubble">到了！</div></div><div class="msg"><div class="avatar">主任</div><div class="bubble">昨天你們反映桌椅不夠，可以去後棟搬喔。</div></div><div class="msg"><div class="avatar">主任</div><div class="bubble">後棟很久沒用了，所以平常鎖著；你們可以用昨天拿到的側門鑰匙進去搬。</div></div><div class="msg"><div class="avatar">主任</div><div class="bubble">桌椅在右邊第一間教室，搬完記得把側門鎖好。</div></div>'}
function sendArrival(){const m=$('#messages');m.innerHTML='<div class="msg"><div class="avatar">主任</div><div class="bubble">你們到學校了嗎？</div></div><div class="msg me"><div class="bubble">到了！</div></div>';const replies=['昨天你們反映桌椅不夠，可以去後棟搬喔。','後棟很久沒用了，所以平常鎖著；你們可以用昨天拿到的側門鑰匙進去搬。','桌椅在右邊第一間教室，搬完記得把側門鎖好。'];let i=0;const add=()=>{if(i===replies.length){state.briefRead=true;const b=document.createElement('button');b.className='send-report';b.textContent='收起手機';b.onclick=()=>{hideAll();say([{s:'艾莉',t:'訊息看到了？那我們先去搬桌椅。'}],()=>showScene('campus'))};m.append(b);return}setTimeout(()=>{m.innerHTML+=`<div class="msg"><div class="avatar">主任</div><div class="bubble">${replies[i++]}</div></div>`;m.scrollTop=m.scrollHeight;add()},430)};add()}
function sendReport(){state.reported=true;const m=$('#messages');m.innerHTML+=`<div class="msg me"><div class="bubble">主任，後棟側門沒有鎖緊，裡面有小孩子大小的腳印和零食包裝碎屑。我們昨天離開時有確實鎖門。</div></div>`;const replies=['我先查一下鑰匙登記。照紀錄，除了你們，應該只有總務有備份。','我會立刻請總務確認門鎖。營隊期間先不要讓孩子靠近後棟。','你們先把桌椅搬回來，等等孩子就要報到了。'];let i=0;const add=()=>{if(i===replies.length){const b=document.createElement('button');b.className='send-report';b.textContent='收起手機';b.onclick=()=>{hideAll();say([{s:'艾莉',t:'至少學校會處理門鎖。先把桌椅搬走，等等也要注意孩子別往這裡跑。'}],teamArrival)};m.append(b);return}setTimeout(()=>{m.innerHTML+=`<div class="msg"><div class="avatar">主任</div><div class="bubble">${replies[i++]}</div></div>`;m.scrollTop=m.scrollHeight;add()},450)};add()}
function shoePuzzle(){choose('你已經看過兩張照片。哪個判斷最合理？',[{label:'賴安去過後棟，所以腳印一定是他的',value:'wrong1'},{label:'鞋底紋路不同，早上的腳印不是賴安留下的',value:'right'},{label:'只要鞋子大小接近，就能確定是他',value:'wrong2'}],v=>{track('shoe_conclusion',{choice:v});if(v!=='right'){toast('再比對一次兩張照片的鞋底紋路。');setTimeout(shoePuzzle,850);return}state.clues.add('shoes');updateCount();say([{s:'艾莉',t:'賴安的鞋底是水平橫紋，後棟泥腳印卻是鋸齒格狀。不是他的。'},{s:'你',t:'所以他雖然去了後棟，卻不是早上留下腳印的人。'},{s:'艾莉',t:'那他為什麼要騙我們說去廁所？'}],revealTruth)})}
function revealTruth(){say([{t:'回到教室收拾黏土工具時，賴安低著頭捲保鮮膜，忽然小聲叫住你。',img:'clay-cleanup-laian.webp'},{s:'賴安',t:'隊輔老師，你不會跟我媽講喔？'},{s:'你',t:'你是說剛才跑去後棟的事？'},{s:'賴安',t:'我真的只是去看獨角仙，沒有去弄那扇門。'},{s:'你',t:'那你為什麼一開始不直接說？'},{s:'賴安',t:'我怕你覺得我很幼稚，都五年級了還在追蟲。'},{s:'你',t:'喜歡獨角仙不幼稚。但你說要去廁所，卻自己跑到別的地方，大家會擔心，也可能遇到危險。'},{s:'賴安',t:'……我知道了。下次我會先講。'},{t:'你這才發現：他確實說了謊，但「說謊」並不能解釋整件事，更不能直接證明腳印是他的。'}],()=>{state.clues.add('truth');updateCount();finalReflection()})}
function finalReflection(){choose('回頭看早上的事情，你現在會怎麼記下賴安？',[{label:'他就是一個會說謊、亂跑的孩子',value:'label'},{label:'他確實做錯事，但還需要理解他為什麼不敢說實話',value:'half'},{label:'既然是看獨角仙，就不需要提醒他安全問題',value:'excuse'}],v=>{track('laian_reflection',{choice:v});const feedback=v==='half'?'行為需要被處理，但一個行為並不足以定義整個孩子。':v==='label'?'這個判斷只看見他的行為，還沒有看見他不敢說出口的原因。':'理解他的原因，不代表忽略離隊帶來的安全風險。';say([{t:feedback},{t:'15:00，第一天的活動結束，孩子們背起書包準備賦歸。'}],()=>showScene('dismissal'))})}
function drawingPuzzle(){say([{s:'你',t:'芮琪，妳在畫今天的活動嗎？',img:'day2-richi-drawing-consistent.webp'},{s:'芮琪',t:'不完全是。我每週上畫畫課，媽媽也會準備畫本。'},{s:'你',t:'我可以看看這張嗎？'},{t:'她把速寫本轉向你。畫上是幾個牽手的孩子。'},{t:'仔細看看，哪裡和現在的第三小隊對不上？',img:'day2-richi-reveal-consistent.webp'}],()=>showScene('day2drawingReveal'))}
function alanConversation(){say([{s:'你',t:'等等，你是……',img:'day2-alan-hidden.webp'},{t:'男孩先往後退了一步。這時連恩、賴安、洛祈和芮琪也從教室方向跑了過來。',img:'day2-alan-talk.webp'},{s:'連恩',t:'隊輔老師，他是阿龍！以前我們五個都在同一隊。'},{s:'賴安',t:'我昨天有看到他。我怕說了以後，你們就不讓他再過來。'},{s:'洛祈',t:'我們只是想跟他聊一下今天玩了什麼。'},{s:'芮琪',t:'他不是陌生人。畫裡第五個人就是他。'},{s:'阿龍',t:'對不起，我沒有要弄壞東西。我只是想來看看他們。'},{s:'你',t:'你以前也參加過營隊？'},{s:'阿龍',t:'嗯，去年我們五個同隊。後來家裡發生了一些事，很多原本可以做的事情都得先停下來，今年就沒有報名。'},{s:'阿龍',t:'其實我剛剛一直在想……明天是最後一天，我也想跟大家一起參加一下。'},{s:'阿龍',t:'不用很久，能跟他們一起玩一會兒就好了。'},{t:'你一時說不出「好」或「不行」。'}],openDayTwoDirectorLine)}
function openDayTwoDirectorLine(){hideAll();$('#phone').classList.remove('hidden');state.phoneMode='day2';state.phoneView='chat';$('#phoneTitle').textContent='營隊主任';const m=$('#messages');m.innerHTML='<div class="msg"><div class="avatar">主任</div><div class="bubble">下午的活動還順利嗎？</div></div><button class="send-report" id="askAlan">詢問阿龍能否參加最後一天</button>';$('#askAlan').onclick=()=>{m.innerHTML+='<div class="msg me"><div class="bubble">主任，我們找到之前留下腳印的孩子了。他叫阿龍，是四個孩子以前的朋友。他想參加明天最後一天，可以嗎？</div></div>';const replies=['我知道這個孩子，但他不在這次營隊名單裡，餐點、材料和保險資料都沒有登記。','如果要補登最後一天，家長必須在今天下班前親自來學校填同意書，也要確認健康資料和接送人。','他的媽媽可能不方便特地跑一趟。你們先把孩子能來的時間問清楚；若方案排得出來，我再陪你們向家長說明。'];let i=0;const add=()=>{if(i===replies.length){const b=document.createElement('button');b.className='send-report';b.textContent='收起手機，詢問阿龍';b.onclick=alanLimits;m.append(b);return}setTimeout(()=>{m.innerHTML+=`<div class="msg"><div class="avatar">主任</div><div class="bubble">${replies[i++]}</div></div>`;m.scrollTop=m.scrollHeight;add()},430)};add()}}
function alanLimits(){hideAll();photo.style.backgroundImage='url("day2-alan-talk.webp")';say([{s:'你',t:'主任說，媽媽今天下班前要到校補資料。你明天什麼時候能來？'},{s:'阿龍',t:'早上要顧弟弟，媽媽中午能載我來，大概十一點到一點。但她下班很累，還要接弟弟，不一定願意再跑學校。'},{s:'你',t:'我們先排清楚時間、餐點和照顧方式，再和主任一起向媽媽說明。你沒有過敏，材料也能和大家共用，對嗎？'},{s:'阿龍',t:'對。'},{t:'16:20，教室只剩你和艾莉。桌上是阿龍遇到的四個問題，以及主任能提供的時間、備用金與隊輔空檔。',img:'day2-planning-table.webp'}],startPlanner)}
const roleProfiles={
 story:{icon:'🎨',name:'故事轉譯者',color:'#ff8f70',fit:'你傾向先讓人理解「為什麼」，相信文字、影像與清楚說明能降低偏見。',strength:'你能讓被制度忽略的人重新被看見，也善於把複雜議題轉成他人願意靠近的故事。',blind:'故事能打開理解，卻不能單獨替代餐點、保險與人力等行政解法。',actions:[['5 分鐘','讀一個現場故事','從 TFT 故事棧挑一篇，記下最改變你想法的一句話。','現在就讀','https://www.teach4taiwan.org/challenge/stories/'],['30 分鐘','把故事說給另一個人','用100字或一張限時動態，說清楚孩子遇到的不是單一問題。','開啟故事素材','https://www.teach4taiwan.org/challenge/stories/'],['本週','發起一次小型共讀','找兩位朋友讀同一篇故事，各自說出原本忽略的一個限制。','選一篇共讀','https://www.teach4taiwan.org/challenge/stories/']],resources:[
  ['TFT 故事棧','選一個打動你的教育現場故事，轉述給身邊的人。','https://www.teach4taiwan.org/challenge/stories/'],
  ['給畢業班孩子們的一封信','看見老師與孩子在兩年陪伴中累積的真實情感。','https://www.teach4taiwan.org/給畢業班孩子們的一封信/'],
  ['Never Out of Reach','從亞洲偏遠社區的學校，看見教育如何回應地方處境。','https://www.channelnewsasia.com/watch/never-out-reach']]},
 resource:{icon:'📊',name:'資源觀察者',color:'#62c7c5',fit:'你習慣先盤點限制、程序與代價，再找出最可持續的資源配置。',strength:'你不容易被一次性的感動沖昏頭，會追問方案是否安全、可複製、能被驗證。',blind:'若過度等待完整資料，可能錯過孩子此刻只有兩小時的參與窗口。',actions:[['5 分鐘','看懂一組關鍵資料','閱讀數位落差專題的開頭，找出硬體以外的兩種差距。','開始閱讀','https://www.twreporter.org/a/covid-19-education-opportunity-inequality'],['30 分鐘','做一張參與門檻清單','挑一個你參加過的活動，列出費用、交通、時間、設備與照顧責任。','查看案例','https://humanityisland.nccu.edu.tw/chenwanqi_a/'],['本週','替一次活動做小改版','問一位沒參加過的人卡在哪裡，再修改一項報名或參與規則。','理解影響評估','https://humanityisland.nccu.edu.tw/chenwanqi_a/']],resources:[
  ['《報導者》：數位落差不只是硬體落差','理解家庭照顧與數位素養如何繼續拉開差距。','https://www.twreporter.org/a/covid-19-education-opportunity-inequality'],
  ['人文島嶼：TFT 影響力研究','從研究與成效評估理解長期影響。','https://humanityisland.nccu.edu.tw/chenwanqi_a/'],
  ['華藝：TFT 案例研究','適合進一步研究教育不平等與師資培育。','https://www.airitilibrary.com/Article/Detail/18144810-N202403300015-00002']]},
 support:{icon:'🤝',name:'陪伴支持者',color:'#ffc857',fit:'你最先注意人的感受與信任，願意成為孩子在現場能依靠的大人。',strength:'你能察覺孩子沒有說出口的擔心，也願意提供穩定、不居高臨下的陪伴。',blind:'若所有問題都靠個人多做一點，陪伴者容易耗盡，制度也不會因此改變。',actions:[['5 分鐘','練習一句不貼標籤的問法','把「他就是不認真」改寫成：「是不是有什麼事，讓你今天很難完成？」','看陪伴者故事','https://www.teach4taiwan.org/成為一位老師，該是什麼模樣？/'],['30 分鐘','聽一位現場工作者說話','讀完一篇教師訪談，記下陪伴者也需要的支持。','閱讀第一線分享','https://www.seinsights.asia/article/9369'],['本週','找一次真實陪伴機會','詢問學校、社區或可信任的組織，有沒有說明完整的短期志工體驗。','認識 TFT','https://www.teach4taiwan.org/']],resources:[
  ['「當老師」能成為值得的選擇嗎？','理解陪伴孩子之前，現場工作者需要哪些關鍵支持。','https://www.teach4taiwan.org/「當老師」能成為值得的選擇嗎？一起聊聊教育現場需要的關鍵支持/'],
  ['成為一位老師，該是什麼模樣？','陪伴不是高高在上的給予，而是一起找答案。','https://www.teach4taiwan.org/成為一位老師，該是什麼模樣？/'],
  ['社企流：第一線教師看見的不平等','傾聽現場陪伴者如何理解孩子與社會問題。','https://www.seinsights.asia/article/9369']]},
 cross:{icon:'🧩',name:'跨域解題者',color:'#a98bff',fit:'你傾向重新組合規則、人力與角色，讓不同資源彼此接上。',strength:'你不把問題只丟給某一位老師或某一筆預算，而會尋找系統間可以重新連線的地方。',blind:'跨域方案需要溝通與維護；若沒有清楚負責人，漂亮的整合可能停在構想。',actions:[['5 分鐘','畫出問題的四個連結','寫下家庭、學校、交通與社區，分別如何影響同一個孩子。','先看系統觀點','https://www.youtube.com/watch?v=3jaTB7hQduE'],['30 分鐘','重新設計一條規則','挑一個熟悉活動，把固定到場改成分段、替代角色或多種參與方式。','取得靈感','https://vocus.cc/article/601c0b08fd89780001a08958'],['本週','邀請不同專長的人解同一題','找教育、設計或數據背景的朋友，各提出一個低成本做法。','認識長期行動','https://www.teach4taiwan.org/']],resources:[
  ['當教育創新作為一種社會運動','從系統視角理解教育不只是學校內部的事。','https://www.youtube.com/watch?v=3jaTB7hQduE'],
  ['地方創生如何回應教育不平等','把教育放回地方產業、人口與社區照顧脈絡。','https://vocus.cc/article/601c0b08fd89780001a08958'],
  ['TFT 兩年計畫','把自己的跨域專業帶進長期教育行動。','https://www.teach4taiwan.org/']]}
};
const planSteps=[
 {title:'① 選擇參與形式',context:'阿龍最多有兩小時，但不一定要用同一種方式加入。你要先決定他和小隊會一起經歷什麼。',options:[
  {label:'完整加入原小隊的半日流程',detail:'補齊聯絡、健康與接送資料後，阿龍從報到、活動、午餐到收尾都跟第三小隊一起進行。',limit:'媽媽必須在今天下班前親自跑一趟學校，把同意書、健康資料與接送文件簽好；她下班後還要接弟弟，可能不願意再特地過來。',cost:{plan:28,staff:8,budget:20},mode:'full',roles:['resource','cross']},
  {label:'只參加一個完整合作活動站',detail:'阿龍為一個50分鐘的合作站報到；隊輔重新說明規則，讓五個孩子完整開始、完成並分享。',limit:'能完整參與一件事，但不會加入午餐與其他活動；隊輔需全程留在該站。',cost:{plan:20,staff:10,budget:10},mode:'focused',roles:['support','resource']},
  {label:'參加放學前的小隊延伸活動',detail:'原營隊流程結束後，兩位隊輔帶五個孩子在約定區域完成一段40至60分鐘的小隊紀念活動。',limit:'活動必須輕量、可攜且由家長同意；四個原小隊員的接送時間也要重新確認。',cost:{plan:24,staff:8,budget:25},mode:'bridge',roles:['cross','story']}]},
 {title:'② 決定實際參與時間',context:'依照你選擇的參與形式，再決定要保留多少時間，以及哪一段體驗最完整。',options:[
  {label:'使用完整120分鐘',detail:'11:00報到，先參加合作活動，12:00一起午餐，12:35完成小隊收尾，12:55準備接送。',limit:'行程最完整，但需要餐點、個人材料與準時銜接；任何延誤都會壓縮收尾。',cost:{plan:24,staff:6,budget:20},minutes:120,mode:'full',roles:['cross','resource']},
  {label:'集中完成70分鐘合作站',detail:'11:20報到，11:30開始50分鐘合作任務，12:20分享成果，12:30由家長接走。',limit:'不用重排整個上午，但只會完成一個活動站，也不包含營隊午餐。',cost:{plan:18,staff:8,budget:15},minutes:70,mode:'focused',roles:['support','story']},
  {label:'保留最後60分鐘共同收尾',detail:'12:00報到，12:10開始製作小隊紀念作品，12:45分享，13:00準時接送。',limit:'參與時間最短，不會體驗原有關卡；必須讓這60分鐘本身有完整開始與結束。',cost:{plan:12,staff:6,budget:10},minutes:60,mode:'bridge',roles:['story','cross']}]},
 {title:'③ 餐點與材料',context:'時段跨過午餐，阿龍也需要一份不用向別人借的材料。',options:[
  {label:'向原餐商追加餐盒＋一份個人材料',detail:'先確認過敏資訊、餐盒內容與送達時間，再從臨時備用金支出。',limit:'必須在餐商截止時間前完成追加；會使用最多備用金。',cost:{plan:18,staff:1,budget:95},mode:'full',meal:'lunch',roles:['resource','support']},
  {label:'使用備用點心＋公用材料桌',detail:'盤點未拆封點心、紙張與彩筆，確認份量後設成全隊共用。',limit:'點心只能暫時墊胃，不能代替午餐；必須先確認阿龍到場前已吃過東西。',cost:{plan:12,staff:2,budget:45},mode:'focused',meal:'snack',roles:['resource','cross']},
  {label:'只準備瓶裝水＋現有材料',detail:'不另外購買餐點，直接使用現場剩餘紙張、色筆與飲水。',limit:'11:00跨過午餐會餓，因此報到必須延後到12:00；實際參與只剩60分鐘。',cost:{plan:8,staff:0,budget:20},mode:'bridge',meal:'water',roles:['story','resource']}]},
 {title:'④ 讓他怎麼加入',context:'不是替阿龍搶走別人的位置，而是增加任何人都能加入的方式。',options:[
  {label:'在原活動增加可隨時加入的任務',detail:'把拍照紀錄、抽題與材料管理列成公開選項，不必排練兩天也能參與。',limit:'隊輔要先把任務規則寫清楚，避免只有熟悉流程的孩子能選。',cost:{plan:24,staff:10,budget:20},mode:'full',roles:['cross','support']},
  {label:'安排固定夥伴一起完成一站',detail:'先由隊輔說明規則，再讓阿龍和熟悉的朋友結伴完成；安全與流程仍由隊輔負責。',limit:'只能完整參與一站，且隊輔必須保留時間在旁確認兩人進度。',cost:{plan:16,staff:8,budget:10},mode:'focused',roles:['support','story']},
  {label:'用五人作品交換作為共同結尾',detail:'每個人完成一張小卡，最後輪流交換並說一句想留給朋友的話。',limit:'需要保留至少30分鐘製作與10分鐘分享，前段活動一延誤就必須縮短。',cost:{plan:20,staff:6,budget:25},mode:'bridge',roles:['story','support']}]}];
const resourceNames={plan:'規劃時間',budget:'臨時備用金',staff:'隊輔可調度空檔'};
const resourceUnits={plan:'分鐘',budget:'元',staff:'分鐘'};
const outcomeProfiles={
 full:{title:'一起完成的最後一天',img:'day3-hug-consistent.webp',impact:'你重新移動了原本的流程。阿龍在自己的兩小時裡，有餐點、有材料，也和朋友完成同一場活動。',child:'五個孩子把共同完成的感謝小卡遞給你。阿龍忽然抱住你，小聲說：「謝謝你真的讓我一起玩。」其他人也笑著靠了過來。'},
 focused:{title:'時間不長，也能完整參與',img:'day3-task-card-consistent.webp',impact:'你沒有要求阿龍追上所有進度，而是保留一段有開始、有合作、有結尾的任務。',child:'阿龍把完成的任務小卡交給你，指著桌上的最後一塊拼圖：「我本來以為只能來看一下，結果這題是我們一起解開的。」'},
 bridge:{title:'一段完整的小隊收尾',img:'day3-memory-board-consistent.webp',impact:'你把最後一段改成不需要前兩天排練也能加入的小隊收尾，並安排在方便接送的遮蔭區。阿龍依照明確的集合與接送時間加入，五個孩子完成同一份紀念作品。',child:'五個孩子一起舉起綁滿彩帶的紀念板。芮琪說：「這不是我們替阿龍做的，是我們五個一起完成的。」'},
 keepsake:{title:'把隊輔也留進回憶裡',img:'day3-group-photo-consistent.webp',impact:'你設計了任何人都能加入的作品交換圈。最後，孩子們不只留下自己的作品，也主動替隊輔留了一個位置。',child:'洛祈把拍立得放上桌，拉著你和艾莉站進隊伍：「你們不能只拍我們啦，你們也有參加！」快門亮起時，七個人都在同一張照片裡。'}
};
function startPlanner(){markCheckpoint('planning');state.plannerStep=0;state.decisions=[];state.outcome='';state.resources={plan:90,budget:150,staff:30};state.scores={story:0,resource:0,support:0,cross:0};hideAll();$('#hud').classList.add('hidden');photo.style.backgroundImage='url("day2-planning-table.webp")';$('#planner').classList.remove('hidden');renderPlannerQuestion()}
function renderResourceBoard(){const max={plan:90,budget:150,staff:30},icons={plan:'⏱',budget:'＄',staff:'🙋'};$('#resourceBoard').innerHTML=Object.keys(resourceNames).map(k=>`<div class="resource-meter ${state.resources[k]<=max[k]*.2?'low':''}"><span class="meter-icon">${icons[k]}</span><small>${resourceNames[k]}</small><b>${k==='budget'?'NT$ ':''}${state.resources[k]} <em>${k==='budget'?'':resourceUnits[k]}</em></b><i class="meter-track"><u style="width:${Math.max(0,state.resources[k]/max[k]*100)}%"></u></i></div>`).join('')}
function renderPlanSlots(){const names=['參與形式','參與時間','餐點材料','加入方式'],icons=['01','02','03','04'];$('#planSlots').innerHTML=names.map((n,i)=>`<div class="plan-slot ${state.decisions[i]?'filled':''}"><i>${state.decisions[i]?'✓':icons[i]}</i><small>${n}</small><b>${state.decisions[i]?.label||'等待選擇'}</b></div>`).join('')}
function costText(cost){return Object.entries(cost).filter(([,v])=>v).map(([k,v])=>`<i>${resourceNames[k]} −${k==='budget'?'NT$ ':''}${v} ${k==='budget'?'':resourceUnits[k]}</i>`).join('')||'<i>不消耗額外資源</i>'}
function canAfford(o){return Object.entries(o.cost).every(([k,v])=>state.resources[k]>=v)}
function renderPlannerQuestion(){renderResourceBoard();renderPlanSlots();const q=planSteps[state.plannerStep];$('#plannerQuestion').innerHTML=q.title;$('#plannerOptions').innerHTML=`<div class="question-context">${q.context}</div>`;$('#decisionFeedback').classList.add('hidden');q.options.forEach(o=>{const ok=canAfford(o),b=document.createElement('button');b.className='planner-choice plan-card';b.disabled=!ok;b.innerHTML=`<b>${o.label}</b><small>${o.detail}</small><span class="plan-limit"><strong>現實限制</strong>${o.limit}</span><small class="choice-cost">${costText(o.cost)}</small>${ok?'':'<span class="unavailable">目前資源不足</span>'}`;b.onclick=()=>selectPlannerOption(o);$('#plannerOptions').append(b)});$('#plannerProgress').innerHTML=`方案卡 ${state.plannerStep+1} / ${planSteps.length}${state.plannerStep?'<button id="undoPlan" class="undo-plan">更換上一張</button>':''}`;$('#undoPlan')?.addEventListener('click',undoPlan)}
function selectPlannerOption(o){track('plan_choice',{step:state.plannerStep+1,option:o.label,mode:o.mode||'none'});state.decisions.push(o);Object.entries(o.cost).forEach(([k,v])=>state.resources[k]-=v);o.roles.forEach((r,i)=>state.scores[r]+=i?1:2);state.plannerStep++;if(state.plannerStep<planSteps.length){renderPlannerQuestion();return}renderPlanReview()}
function undoPlan(){const o=state.decisions.pop();if(!o)return;Object.entries(o.cost).forEach(([k,v])=>state.resources[k]+=v);o.roles.forEach((r,i)=>state.scores[r]-=i?1:2);state.plannerStep--;renderPlannerQuestion()}
function renderPlanReview(){renderResourceBoard();renderPlanSlots();$('#plannerQuestion').textContent='方案已經拼好了';$('#plannerOptions').innerHTML='';const f=$('#decisionFeedback');f.classList.remove('hidden');f.innerHTML=`<h3>明天，阿龍會怎麼參與？</h3><p>你用掉了 ${90-state.resources.plan} 分鐘規劃時間、NT$ ${150-state.resources.budget} 臨時備用金與 ${30-state.resources.staff} 分鐘隊輔空檔。</p><p>現在還差最後一道門檻：由你和主任打給媽媽，說明確切安排，請她在今天下班前到校補登最後一天。</p><button id="executePlan">打給阿龍媽媽</button><button id="changePlan" class="soft-action">更換最後一張</button>`;$('#plannerProgress').textContent='第二天離校前，做出決定';$('#executePlan').onclick=finalizeDayTwoPlan;$('#changePlan').onclick=undoPlan}
function finalizeDayTwoPlan(){const meal=state.decisions[2].meal,time=state.decisions[1].mode;const arrival=meal==='water'||time==='bridge'?'12:00':time==='focused'?'11:20':'11:00';const planSummary={form_mode:state.decisions[0].mode,time_mode:time,meal_mode:meal,participation_mode:state.decisions[3].mode,planning_minutes_left:state.resources.plan,budget_ntd_left:state.resources.budget,staff_minutes_left:state.resources.staff,predicted_outcome:calculateOutcome()};track('plan_completed',planSummary);hideAll();photo.style.backgroundImage='url("day2-planning-table.webp")';say([{t:'第二天，16:35。主任把電話切成擴音，你向阿龍媽媽說明明天的集合、接送、餐點與照顧方式。',img:'day2-planning-table.webp'},{s:'阿龍媽媽',t:'一定要今天去嗎？我下班還要接小的，明天中午也只能請一小段假。'},{s:'你',t:`我們知道很趕。資料今天補齊後，阿龍明天${arrival}報到，最晚13:00由您接走；這段時間會由我和艾莉負責。`},{s:'營隊主任',t:'我會把需要填的地方先標好，也留在學校等您。到了核對資料、簽名就可以。'},{s:'阿龍媽媽',t:'好，那我接完弟弟繞過去。麻煩你們了。'},{t:'17:42，阿龍媽媽牽著弟弟趕到學校。主任核對健康資料與接送人，完成最後一天的補登。'},{t:'你把確認結果打給阿龍。他在電話另一頭停了兩秒，才很大聲地說：「好！我會準時到！」'},{t:'第二天的調查到這裡告一段落。你們找到的，不只是留下腳印的人，也是一連串讓他無法參加的限制。'}],()=>{localStorage.setItem('clockSavedPlan',JSON.stringify({decisions:state.decisions,resources:state.resources,scores:state.scores}));completeDay(2,{predicted_outcome:planSummary.predicted_outcome});unlockDay(3);page('endingTwo')})}
function calculateOutcome(){const counts={full:0,focused:0,bridge:0};state.decisions.forEach(d=>counts[d.mode]++);if(state.decisions[2].meal==='water'||state.decisions[0].mode==='bridge')return'bridge';if(state.decisions[3].mode==='bridge')return'keepsake';return counts.focused>counts.full?'focused':'full'}
function playDayThreeOutcome(){
 state.outcome=calculateOutcome();const o=outcomeProfiles[state.outcome];hideAll();photo.style.backgroundImage='url("day2-planning-table.webp")';
 const form=state.decisions[0].mode,time=state.decisions[1].mode,meal=state.decisions[2].meal,join=state.decisions[3].mode;
 const arrival=meal==='water'||time==='bridge'?'12:00':time==='focused'?'11:20':'11:00';
 const common=[{t:`第三天，${arrival}。阿龍背著書包出現在約定的地方。四個朋友一看到他，立刻朝他跑了過去。`,img:'day3-arrival.webp'}];
 const formScenes={
  full:[{t:'你把阿龍的名牌貼進第三小隊欄位，重新帶他走一次報到、置物與活動規則。原流程稍微慢了下來，但他不必猜自己現在該站在哪裡。'}],
  focused:[{t:'你沒有要求阿龍追上前兩天的所有進度，而是留下一個完整合作站。五個孩子重新聽過規則後，從同一張起點卡開始。',img:'day3-task-card-consistent.webp'}],
  bridge:[{t:'原營隊流程告一段落後，你和艾莉在遮蔭區展開一個獨立的小隊活動。阿龍不必補做前兩天的內容，也能從頭參與。',img:'day3-bridge-setup-consistent.webp'}]
 };
 const timeScenes={
  full:{t:'完整的兩小時讓阿龍經歷報到、合作、午間休息與分享；你也在12:55提醒大家收尾，沒有耽誤媽媽接送。'},
  focused:{t:'這70分鐘沒有塞入太多關卡。五個孩子只做一件合作任務，卻有時間一起開始、卡關，再一起完成。'},
  bridge:{t:'只剩60分鐘，你刪掉暖場與重複說明，把時間留給製作和分享。阿龍沒有參加很多項目，但完整完成了一項。'}
 };
 const mealScenes={
  lunch:{t:'12:00，阿龍拿到事先追加、寫著他名字的餐盒與個人材料。他沒有向任何人借一份，和朋友坐在同一桌吃完午餐。'},
  snack:{t:'11:50，阿龍肚子餓了。你拿出事先確認過的備用點心讓他先墊胃，並把分享縮短十分鐘，讓他能準時回家吃正餐。'},
  water:{t:'因為只有飲水，阿龍先在家吃過午餐，12:00才到。這避開了挨餓，代價是他錯過前段流程，只能參與最後60分鐘。'}
 };
 const joinScenes={
  full:[{t:'你把紀錄、抽題和材料管理寫成三張公開任務卡。阿龍選了拍照紀錄，洛祈也改選抽題；新增的入口不只幫到一個人。',img:'day3-task-card-consistent.webp'},{s:'阿龍',t:'我不是被安排坐旁邊耶，我有自己的工作。'}],
  focused:[{t:'連恩自願成為阿龍的固定夥伴。兩人一起確認題目，但答案必須由五個人討論後才能送出。',img:'day3-task-card-consistent.webp'},{s:'連恩',t:'你昨天沒玩到沒關係，這一關我們一起開始。'}],
  bridge:[{t:'每個孩子各畫一張小卡，再輪流交換。阿龍拿到芮琪畫的五人圖，也把自己的卡交給了你。',img:'day3-memory-board-consistent.webp'},{s:'阿龍',t:'這張不是補給我的，是我們今天一起做的。'}]
 };
 const feedback={
  full:[{t:'12:50，五個孩子把共同完成的任務紀錄折成一本小冊子，封面寫著「第三小隊，五人到齊」。'},{s:'賴安',t:'隊輔老師，這本給你。因為你真的有把我們缺的那一個位置想進去。'}],
  focused:[{t:'活動結束時，阿龍把最後一塊任務拼圖按進板子，再請四個朋友在完成卡背面簽名。'},{s:'阿龍',t:'我本來以為只能來看一下，結果這題真的是我們一起解開的。'}],
  bridge:[{t:'五張卡被繫到同一塊紀念板上。芮琪指著正中央那張五人圖，大家一起叫你過去看。'},{s:'芮琪',t:'昨天我只敢畫在自己的本子裡。今天這張，是我們真的一起完成的。'}]
 };
 say([...common,...formScenes[form],timeScenes[time],mealScenes[meal],...joinScenes[join],...feedback[form]],playClosingReflection)
}
function playClosingReflection(){say([{t:'13:00，接送時間到了。五個孩子背起書包，拿著剛完成的作品走到穿堂；阿龍的媽媽也剛好趕到。',img:'day3-pickup-consistent.webp'},{t:'你向媽媽確認接送資料，阿龍已經迫不及待地把作品舉到她面前。'},{s:'阿龍媽媽',t:'我們家最近的工作和收入都不太穩定，我只好多排一些班。阿龍放學後常要幫忙顧弟弟，我也沒有辦法每天接送他。'},{s:'阿龍媽媽',t:'營隊的費用、交通和時間一起碰上，我們就很難排出能配合的方法。昨天你們把安排說清楚，我才知道今天還有辦法讓他來。謝謝你們。'},{t:'鐘聲響起。五個孩子一邊約下次見，一邊走向各自的接送人。阿龍走了幾步，又回頭朝你和艾莉揮了揮手。'},{s:'你',t:'我只是多問了一句，再重新安排時間和需要的東西，阿龍今天就多了一個能參與的位置。'},{t:'你無法一次改變所有條件，但可以先看見限制，從自己做得到的一步開始。'}],showRoleResult)}
function showRoleResult(){const order=['story','resource','support','cross'],max=Math.max(...order.map(k=>state.scores[k])),tied=order.filter(k=>state.scores[k]===max);let key=tied[0];for(const d of [...state.decisions].reverse()){const found=d.roles.find(k=>tied.includes(k));if(found){key=found;break}}const r=roleProfiles[key],o=outcomeProfiles[state.outcome];completeDay(3,{outcome:state.outcome});track('game_completed',{outcome:state.outcome,total_duration_seconds:elapsedSeconds(state.gameStartedAt)});track('persona_result',{persona:key,persona_name:r.name});const actions=r.actions.map((x,i)=>`<article class="action-mission ${i===0?'featured':''}"><span>${x[0]}</span><h3>${x[1]}</h3><p>${x[2]}</p><div><button class="commit-action" data-action="${i}">選這一步</button></div></article>`).join('');hideAll();$('#hud').classList.add('hidden');photo.style.backgroundImage=`url("${o.img}")`;$('#result').style.setProperty('--role',r.color);$('#result').classList.remove('hidden');$('#resultContent').innerHTML=`<section class="role-hero"><div class="role-icon">${r.icon}</div><p class="eyebrow">你的行動者傾向</p><h2>${r.name}</h2><p>${r.fit}</p></section><section class="result-summary"><h3>你的分析結果</h3><p><b>你擅長的方式：</b>${r.strength}</p><p><b>行動時可以留意：</b>${r.blind}</p><p>${o.impact}</p></section><section class="action-zone"><p class="action-kicker">從一件做得到的小事開始</p><h2>你現在可以這樣做</h2>${actions}<div id="commitment" class="commitment hidden"></div></section><section class="confidence-check"><p class="action-kicker">最後一個問題</p><h3>玩完故事後，你覺得自己能為教育議題做出一點改變嗎？</h3><div><button data-confidence="know_first_step">我已經知道可以從哪一步開始</button><button data-confidence="learn_more">我願意再了解更多</button><button data-confidence="still_unsure">我仍不確定自己能做什麼</button></div><p id="confidenceFeedback" class="hidden">謝謝你的回答，我們會用這份匿名回饋改善遊戲。</p></section><button id="resultThanks">看完結果，繼續</button><button id="resultHome" class="secondary-result">回到三日營隊紀錄</button>`;$$('.commit-action').forEach(b=>b.onclick=()=>selectImmediateAction(r,Number(b.dataset.action)));$$('[data-confidence]').forEach(b=>b.onclick=()=>selectConfidence(b.dataset.confidence));$('#resultThanks').onclick=showThanks;$('#resultHome').onclick=()=>page('chapters')}
function selectConfidence(answer){track('action_confidence',{answer});$$('[data-confidence]').forEach(b=>{b.disabled=true;b.classList.toggle('selected',b.dataset.confidence===answer)});$('#confidenceFeedback').classList.remove('hidden')}
function selectImmediateAction(role,index){track('action_selected',{persona:role.name,action_index:index});const a=role.actions[index],box=$('#commitment');localStorage.setItem('clockActionCommitment',JSON.stringify({role:role.name,action:a[1],createdAt:new Date().toISOString()}));box.classList.remove('hidden');box.innerHTML=`<b>✓ 你的第一步已經選好了</b><p>${a[0]}｜${a[1]}</p><small>不用一次改變整個世界。先完成這一小步，就已經從「在意」走向「參與」。</small><a id="actionLink" target="_blank" rel="noopener" href="${a[4]}">${a[3]} ↗</a>`;$('#actionLink').onclick=()=>track('action_link_clicked',{persona:role.name,action_index:index});box.scrollIntoView({behavior:'smooth',block:'center'})}
function showThanks(){page('postSurvey')}
function showFinalThanks(){hideAll();$('#hud').classList.add('hidden');photo.style.backgroundImage='url("day3-group-photo-consistent.webp")';$('#thanks').classList.remove('hidden')}
function updateCount(){$('#count').textContent=state.day===2?state.d2clues.size:state.clues.size}
function renderNotes(){const list=$('#noteList');list.innerHTML='';const active=state.day===2?state.d2clues:state.clues;$('#noteDay').textContent=state.day===2?'第二天':'第一天';active.forEach(k=>{if(notes[k])list.innerHTML+=`<div class="note"><b>${notes[k][0]}</b><p>${notes[k][1]}</p></div>`});if(!active.size)list.innerHTML='<p>目前還沒有記下任何異常。</p>';$('#notebook').classList.remove('hidden')}
function toast(t){const x=$('#toast');x.textContent=t;x.classList.remove('hidden');setTimeout(()=>x.classList.add('hidden'),1400)}
function showFlyer(){hideAll();$('#flyer').classList.remove('hidden')}
function confirmFlyer(){choose('要和艾莉一起報名三日營隊嗎？',[{label:'確認參加營隊',value:'yes'},{label:'再看一次招募傳單',value:'again'}],v=>{track('invitation_choice',{choice:v});if(v==='yes')page('nameEntry');else showFlyer()})}
$('#viewFlyer').onclick=showFlyer;
function savePlayerName(){const value=$('#playerName').value.trim();if(!value){$('#nameError').textContent='請先輸入大家可以稱呼你的名字。';return}state.playerName=value;localStorage.setItem('clockPlayerName',value);$('#nameError').textContent='';page('preSurvey')}
$('#confirmName').onclick=savePlayerName;
$('#playerName').addEventListener('keydown',e=>{if(e.key==='Enter')savePlayerName()});
$('#preSurveyOpen').onclick=()=>track('pretest_external_opened');
$('#preSurveyDone').onclick=()=>{sessionStorage.setItem('clockPretestAcknowledged','yes');state.gameStartedAt=Date.now();localStorage.setItem('clockGameStartedAt',String(state.gameStartedAt));track('pretest_completion_acknowledged');track('game_started');page('chapters')};
$('#postSurveyOpen').onclick=()=>track('posttest_external_opened');
$('#postSurveyBack').onclick=()=>{hideAll();$('#result').classList.remove('hidden')};
$('#postSurveyDone').onclick=()=>{localStorage.setItem('clockPosttestAcknowledged','yes');track('posttest_completion_acknowledged');showFinalThanks()};
$('#acceptFlyer').onclick=()=>{hideAll();photo.style.backgroundImage='url("prologue-chat.webp")';say([{s:'艾莉',t:'暑假才第三天，我已經快無聊死了。'},{s:'你',t:'剛剛不是還說想找事情做、順便賺點錢？'},{s:'艾莉',t:'對啊。這個有小朋友、有活動，還有一點隊輔津貼，感覺比在家發霉好吧？'},{t:'你又看了一次招募單：活動共三天，由大專生擔任小隊隊輔。'}],confirmFlyer)};$('#flyerBack').onclick=()=>page('prologue');
$('#dayOne').onclick=()=>{state.gameStartedAt=Date.now();localStorage.setItem('clockGameStartedAt',String(state.gameStartedAt));startDay(1);state.clues.clear();state.children.clear();state.clay.clear();state.briefRead=false;state.reported=false;state.rearIntroSeen=false;state.phoneMode='brief';state.phoneView='home';updateCount();resetSceneHistory();photo.style.backgroundImage='url("hexing-campus.webp")';hideAll();say([{t:'營隊前一天，你和艾莉已經完成場勘，並親手鎖好後棟側門。'},{t:'第一天，07:30。你們提早回到合興國小。'},{t:'穿堂還很安靜，背包裡忽然傳來手機震動。'}],()=>showScene('campus'))};
$('#dayTwo').onclick=()=>{startDay(2);state.d2clues.clear();state.d2talk.clear();state.decisions=[];localStorage.removeItem('clockSavedPlan');updateCount();resetSceneHistory();photo.style.backgroundImage='url("day2-rear-v2.webp")';hideAll();say([{t:'第二天，07:50。你和艾莉再次來到後棟。',img:'day2-rear-v2.webp'},{s:'艾莉',t:'側門重新鎖好了，總務也貼了告示。'},{t:'正要離開時，你們發現花圃泥地多了一串新腳印。'}],()=>showScene('day2rear'))};
$('#dayThree').onclick=()=>{const saved=localStorage.getItem('clockSavedPlan');if(saved){const data=JSON.parse(saved);state.decisions=data.decisions;state.resources=data.resources;state.scores=data.scores}else if(state.decisions.length!==4){toast('先完成第二天的方案規劃。');return}startDay(3);state.gameStartedAt=Number(localStorage.getItem('clockGameStartedAt'))||state.gameStartedAt||Date.now();resetSceneHistory();markCheckpoint('along_arrived');playDayThreeOutcome()};
$('#plannerBack').onclick=()=>page('chapters');
$('#bagBtn').onclick=openBag;$('#bagBack').onclick=()=>showScene('campus');$('#bagPhone').onclick=()=>openPhone('brief');$('#bagMap').onclick=()=>openDocument('map','bag');$('#docBack').onclick=()=>state.docSource==='phone'?openPhone(state.phoneMode):openBag();
function returnFromClue(){showScene(state.phase)}
$('#clueBack').addEventListener('click',returnFromClue);$('#clueReturnBottom').addEventListener('click',returnFromClue);
$('#sceneNext').onclick=()=>{if(state.phase==='team')afterChildren();else if(state.phase==='rear')concernReport();else if(state.phase==='compare')shoePuzzle();else if(state.phase==='day2map')say([{t:'大家重新確認方向後，沿著二樓穿堂找到第二張提示：下一關藏在老榕樹附近。'},{t:'洛祈一看到榕樹就衝到最前面。',img:'day2-explore-tree-v2.webp'},{s:'賴安',t:'等一下啦，大家要一起走！'},{s:'連恩',t:'芮琪，妳幫我們記答案，我去把洛祈叫回來。'},{t:'同一件事裡，每個孩子都用了不同的方法參與。'}],()=>showScene('day2tree'));else if(state.phase==='day2tree'){state.d2clues.add('d2map');updateCount();say([{t:'10:20，校園大探索順利完成。四個孩子靠著不同的方法，拼出了最後一題。'},{s:'艾莉',t:'如果只看誰最快找到答案，會漏掉很多人的功勞耶。'},{s:'你',t:'有人找方向、有人顧隊伍、有人試新的路、也有人把線索記下來。少一個都不行。'},{t:'11:00，水球活動結束。孩子們一身濕，在榕樹下擦頭髮、喝水。芮琪坐在稍遠的樹蔭裡，安靜地畫著畫。',img:'day2-richi-drawing-consistent.webp'}],()=>showScene('day2drawing'))}else if(state.phase==='day2plantkids')say([{t:'孩子們沿著花圃繼續往前調查。你落在隊伍後方，想起早上腳印旁那幾顆黑色種子。',img:'day2-plant-kids-v2.webp'},{t:'13:35，你拿出手機，打開早上拍下的照片，再抬頭比對眼前分散在不同角落的植物。',img:'day2-plant-puzzle-consistent.webp'},{s:'你',t:'如果能找到同一種植物，也許就能知道留下腳印的人是從哪條路過來的。'}],()=>showScene('day2plants'))};
$('#phoneBack').onclick=()=>{if(state.phoneMode==='day2'){alanLimits();return}if(state.phoneView==='chat'){renderContacts();return}if(state.phoneView==='list'){renderPhoneHome();return}if(state.phoneMode==='brief')openBag();else showScene('rear')};
$('#notesBtn').onclick=renderNotes;$('#closeNotes').onclick=()=>$('#notebook').classList.add('hidden');
$('#sceneBack').onclick=()=>{if(sceneHistoryIndex>0){sceneHistoryIndex--;showScene(sceneHistory[sceneHistoryIndex],false)}else page('chapters')};
$('#sceneForward').onclick=()=>{if(sceneHistoryIndex<sceneHistory.length-1){sceneHistoryIndex++;showScene(sceneHistory[sceneHistoryIndex],false)}};
$('#replay').onclick=()=>page('chapters');
$('#finishDayTwo').onclick=()=>page('chapters');
$('#nextDayTwo').onclick=()=>$('#dayTwo').click();
$('#nextDayThree').onclick=()=>$('#dayThree').click();
$('#thanksHome').onclick=()=>page('chapters');
$('#resultBack').onclick=()=>page('chapters');
$('#thanksBack').onclick=()=>page('postSurvey');
const consentPanel=$('#analyticsConsent'),consentStatus=localStorage.getItem('clockAnalyticsConsent');
if(consentStatus==='accepted'){window.posthog?.opt_in_capturing?.()}else if(consentStatus==='declined'){window.posthog?.opt_out_capturing?.()}else{consentPanel.classList.remove('hidden')}
$('#analyticsAccept').onclick=()=>{localStorage.setItem('clockAnalyticsConsent','accepted');window.posthog?.opt_in_capturing?.();consentPanel.classList.add('hidden');window.posthog?.capture?.('analytics_consent',{choice:'accepted',game_version:analyticsVersion});window.posthog?.capture?.('$pageview')};
$('#analyticsDecline').onclick=()=>{localStorage.setItem('clockAnalyticsConsent','declined');window.posthog?.opt_out_capturing?.();consentPanel.classList.add('hidden')};
